substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_pass: !secret wifi_pass
  api: !secret api
  ota: !secret ota

wifi:
  ssid: $wifi_ssid
  password: $wifi_pass
  manual_ip:
    static_ip: $ip_addr
    gateway: $default_gw
    subnet: $subnet
  ap:
    ssid: $dev_name
    password: $ap_pass

captive_portal:

api:
  encryption:
    key: $api

ota:
  password: $ota
  id: my_ota
